/**
 * 
 */

import java.util.*;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

import javax.swing.text.html.HTMLDocument.HTMLReader.IsindexAction;

//Task1

public class Task1 {
	// To get the hash 
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException
    {
        // Static getInstance method is called with hashing SHA
        MessageDigest md = MessageDigest.getInstance("SHA-256");
 
        return md.digest(input.getBytes(StandardCharsets.UTF_8));
    }
     
    
    
    public static String toHexString(byte[] hash)
    {
        // Convert byte array into signum representation
        BigInteger number = new BigInteger(1, hash);
 
        // Convert message digest into hex value
        StringBuilder hexString = new StringBuilder(number.toString(16));
 
        // Pad with leading zeros
        while (hexString.length() < 64)
        {
            hexString.insert(0, '0');
        }
 
        return hexString.toString();
    }
 

// TODO

	// Task1: Print menu 
	public static void main (String[] args){
		
		System.out.println("Great Work");
		System.out.println("\n");
		System.out.println("Select an action:");
		System.out.println("-----------------");
		System.out.println("1) Generate Hash:");
		System.out.println("2) Compare Hash");
		System.out.println("3) Re-compute");


		Scanner input= new Scanner(System.in);
		Scanner input2= new Scanner(System.in);

		System.out.println("Enter your Option:");

		boolean valid=false;

		while (valid==false) {
			int numb=input.nextInt();
			if (numb==1) {
				valid=true;
				System.out.println("Compare Hash");

			}
			else if (numb==2) {
				valid=true;
				System.out.println("Generate Hash");
				
				  try
			        {
					  
			            System.out.println("HashCode Generated by SHA-256 for:");
			            String word=input2.nextLine();
			            System.out.println("\n" + word + " : " + toHexString(getSHA(word)));
		
			        }
			        // For specifying wrong message digest algorithms
			        catch (NoSuchAlgorithmException e) {
			            System.out.println("Exception thrown for incorrect algorithm: " + e);
			        }

			}
			else if (numb==3) {
				valid=true;
				System.out.println("Re-compute");

			}

			else {
				valid=false;
				System.out.println("please, choose from 1 - 3");

			}}
		input.close();

System.out.print("Good Girl");



	} 

}
